
language: node_js
 
node_js:
  - "10"
 
branches:
  only:
    - master

before_install:
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
  - git lfs pull
 
install:
  - npm install
 
script:
  - npm start
 
env:
 global:
   - GH_REF: github.com/xuxia1009/node-grab.git
 
after_script:
  - git config user.name "${GIT_NAME}"
  - git config user.email "${GIT_EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOkEN}@${GH_REF}" master:master