
language: node_js
 
node_js:
  - "10"
 
branches:
  only:
    - dev
 
install:
  - npm install
 
script:
  - npm start
 
env:
 global:
   - GH_REF: github.com/xuxia1009/node-grab.git

 
after_script:
  - git config user.name "xuxia1009"
  - git config user.email "18810986017@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOkEN}@${GH_REF}" master:master